### PR TITLE
APW-3 Registration test cases

### PR DESCRIPTION
**Pull request by Grooptest**
please verify my test work on repository and just for information, this work is only for learning purpose please reply accordingly.

### CODE REVIEW

**Comment by Grooptest** [comment]
hi all

**Comment by Grooptest** [comment]
perfect

**Comment by Dhartiv69** [comment]
good

**Review by Grooptest — COMMENTED** [review]
hi

**Review by Dhartiv69 — APPROVED** [review]
nice job

**Review by Dhartiv69 — APPROVED** [review]
ok

**Review by BhavinGitt — APPROVED** [review]
good

**Pull request merged**
